#
# Helix Configuration
#
version: 1

definitions:
  defaults:
    # default repository. set to git remote repository before deployment
    - &defaultRepo https://github.com/tripodsan/helix-pages.git#master

preflight: https://adobeioruntime.net/api/v1/web/helix/helix-services/version-picker@0.0.1

strains:
  - name: default
    code: *defaultRepo
    content: https://github.com/tripodsan/helix-pages.git#master
    static: https://github.com/tripodsan/helix-pages.git/htdocs#master
    package: tripod/3e0670464bc07f36395ed2eb812fe20e4629f54d

  - name: breaking-december
    condition:
      preflight.x-pages-version=: breaking-december
    code: https://github.com/tripodsan/helix-pages.git#breaking-december
    content: https://github.com/tripodsan/helix-pages.git#breaking-december
    static: https://github.com/tripodsan/helix-pages.git/htdocs#breaking-december
    package: tripod/238dca652557e8200f0268d6e2f33c7bb937251a
    version-lock:
      word2md: 2.1.11-testing

  - name: breaking-january
    condition:
      preflight.x-pages-version=: breaking-january
    code: https://github.com/tripodsan/helix-pages.git#breaking-january
    content: https://github.com/tripodsan/helix-pages.git#breaking-january
    static: https://github.com/tripodsan/helix-pages.git/htdocs#breaking-january
    package: tripod/8dddaf5f4657c9a6843ee1d39cbc2b4e942b5d57
    version-lock:
      word2md: 2.1.11-testing-january
