#
# Helix Configuration
#
version: 1

definitions:
  defaults:
    # default repository. set to git remote repository before deployment
    - &defaultRepo https://github.com/adobe/helix-pages.git#master

strains:
  - name: default
    code: *defaultRepo
    content: https://github.com/adobe/helix-pages.git#master
    static: https://github.com/adobe/helix-pages.git/htdocs#master
    package: helix-pages/409dbb736a15632dd01448e777425c830b3c6c61
  # strain for breaking changes
  - name: breaking-september
    condition:
      url.hostname=: breaking-september--pages--adobe.99productrules.com
    code: https://github.com/adobe/helix-pages.git#breaking-september
    content: https://github.com/adobe/helix-pages.git#breaking-september
    static: https://github.com/adobe/helix-pages.git/htdocs#breaking-september
    package: tripod/64cb37cc8b92486697882c61828b287b80f9c608
    # version-lock: .....
