#
# Helix Configuration
#
version: 1

definitions:
  defaults:
    # default repository. set to git remote repository before deployment
    - &defaultRepo https://github.com/davidnuescheler/helix-test.git#master

strains:
  - name: default
    code: *defaultRepo
    content: https://github.com/davidnuescheler/helix-test.git#master
    static: https://github.com/davidnuescheler/helix-test.git/htdocs#master
    package: acapt/github-com--davidnuescheler--helix-test--master-dirty
