#
# Helix Configuration
#
version: 1

definitions:
  defaults:
    # default repository. set to git remote repository before deployment
    - &defaultRepo https://github.com/adobe/helix-pages.git#master

preflight: https://adobeioruntime.net/api/v1/web/helix/helix-services/version-picker@v1

strains:
  - name: default
    code: *defaultRepo
    content: https://github.com/adobe/helix-pages.git#master
    static: https://github.com/adobe/helix-pages.git/htdocs#master
    package: helix-pages/pages_4.15.4

  - name: universal
    code: *defaultRepo
    content: https://github.com/adobe/helix-pages.git#master
    static: https://github.com/adobe/helix-pages.git/htdocs#master
    # universal runtime, using the helix test deployment subdomain for now.
    package: https://deploy-test.anywhere.run/pages_4.15.4
    version-lock:
      env: amazonwebservices

  - name: breaking-202103
    condition:
      preflight.x-pages-version=: breaking-202103
    code: https://github.com/tripodsan/helix-pages.git#breaking-202103
    content: https://github.com/tripodsan/helix-pages.git#breaking-202103
    static: https://github.com/tripodsan/helix-pages.git/htdocs#breaking-202103
    package: helix-pages/pages_4.15.4.breaking-202103
