#
# Helix Configuration
#
version: 1

definitions:
  defaults:
    # default repository. set to git remote repository before deployment
    - &defaultRepo https://github.com/adobe/helix-pages.git#master

strains:
  - name: default
    code: *defaultRepo
    content: https://github.com/adobe/helix-pages.git#master
    static: https://github.com/adobe/helix-pages.git/htdocs#master
    package: helix-pages/b316d674a1d0b5be59750f20aa8ab0d6f8f08048
  # strain for breaking changes
  - name: breaking-september
    code: https://github.com/adobe/helix-pages.git#breaking-september
    content: https://github.com/adobe/helix-pages.git#breaking-september
    static: https://github.com/adobe/helix-pages.git/htdocs#breaking-september
    # version-lock: .....
