#
# Helix Configuration
#
version: 1

definitions:
  defaults:
    # default repository. set to git remote repository before deployment
    - &defaultRepo https://github.com/tripodsan/helix-pages.git#master

preflight: https://adobeioruntime.net/api/v1/web/helix/helix-services/version-picker@1.0.0

strains:
  - name: default
    code: *defaultRepo
    content: https://github.com/tripodsan/helix-pages.git#master
    static: https://github.com/tripodsan/helix-pages.git/htdocs#master
    package: tripod/3e0670464bc07f36395ed2eb812fe20e4629f54d

  - name: breaking-december
    condition:
      preflight.x-pages-version=: breaking-december
    code: https://github.com/tripodsan/helix-pages.git#breaking-december
    content: https://github.com/tripodsan/helix-pages.git#breaking-december
    static: https://github.com/tripodsan/helix-pages.git/htdocs#breaking-december
    package: tripod/df57ad63d4fb5d4a49f337a2e8ad238d06075e8f
    version-lock:
      word2md: 2.1.11-testing

  # note 1
  - name: breaking-january
    condition:
      preflight.x-pages-version=: breaking-january
    code: https://github.com/tripodsan/helix-pages.git#breaking-january
    content: https://github.com/tripodsan/helix-pages.git#breaking-january
    static: https://github.com/tripodsan/helix-pages.git/htdocs#breaking-january
    package: tripod/af2e26ca17abe9f926291afc59259a275561262d
    version-lock:
      word2md: 2.1.11-testing-january
