#
# Helix Configuration
#
version: 1

definitions:
  defaults:
    # default repository. set to git remote repository before deployment
    - &defaultRepo https://github.com/adobe/helix-pages.git#master

preflight: https://helix-pages.anywhere.run/helix-services/version-picker@v1

strains:
  - name: default
    code: *defaultRepo
    content: https://github.com/adobe/helix-pages.git#master
    static: https://github.com/adobe/helix-pages.git/htdocs#master
    package: https://helix-pages.anywhere.run/pages_7_2_1

  - name: universal
    code: *defaultRepo
    content: https://github.com/adobe/helix-pages.git#master
    static: https://github.com/adobe/helix-pages.git/htdocs#master
    # universal runtime, using the helix test deployment subdomain for now.
    package: https://helix-pages.anywhere.run/pages_7_2_1
    version-lock:
      env: amazonwebservices

  - name: gcf
    code: *defaultRepo
    content: https://github.com/adobe/helix-pages.git#master
    static: https://github.com/adobe/helix-pages.git/htdocs#master
    # universal runtime, on google cloud functions.
    package: https://helix-pages.anywhere.run/pages_7_2_1
    version-lock:
      env: google

  - name: gcf-ci
    code: *defaultRepo
    content: https://github.com/adobe/helix-pages.git#master
    static: https://github.com/adobe/helix-pages.git/htdocs#master
    # universal runtime (CI), on google cloud functions.
    package: https://helix-pages-ci.anywhere.run/pages_7_2_1
    version-lock:
      env: google

  - name: universal-ci
    code: *defaultRepo
    content: https://github.com/adobe/helix-pages.git#master
    static: https://github.com/adobe/helix-pages.git/htdocs#master
    # universal runtime, using the helix-pages-ci subdomain
    package: https://helix-pages-ci.anywhere.run/pages_7_2_1

  - name: universal-prod
    code: *defaultRepo
    content: https://github.com/adobe/helix-pages.git#master
    static: https://github.com/adobe/helix-pages.git/htdocs#master
    # universal runtime, using the helix-pages subdomain
    package: https://helix-pages.anywhere.run/pages_7_2_1

  - name: breaking-202106
    sticky: false
    condition:
      preflight.x-pages-version=: breaking-202106
    code: https://github.com/adobe/helix-pages.git#breaking-202106
    content: https://github.com/adobe/helix-pages.git#breaking-202106
    static: https://github.com/adobe/helix-pages.git/htdocs#breaking-202106
    package: https://helix-pages.anywhere.run/pages_7-2-1-breaking-202106
    version-lock:
      word2md: ci3442

  # temporary strain to test the metadata.json loading from sharepoint
  - name: breaking-800
    sticky: false
    condition:
      preflight.x-pages-version=: breaking-800
    code: https://github.com/adobe/helix-pages.git#breaking-800
    content: https://github.com/adobe/helix-pages.git#breaking-800
    static: https://github.com/adobe/helix-pages.git/htdocs#breaking-800
    package: https://helix-pages.anywhere.run/pages_6-1-0-breaking-800
