#
# Helix Configuration
#
version: 1

definitions:
  defaults:
    # default repository. set to git remote repository before deployment
    - &defaultRepo https://github.com/adobe/helix-pages.git#master

preflight: https://helix-pages.anywhere.run/helix-services/version-picker@v1

strains:
  - name: default
    code: *defaultRepo
    content: https://github.com/adobe/helix-pages.git#master
    static: https://github.com/adobe/helix-pages.git/htdocs#master
    package: https://helix-pages.anywhere.run/pages_7_3_0

  - name: universal
    code: *defaultRepo
    content: https://github.com/adobe/helix-pages.git#master
    static: https://github.com/adobe/helix-pages.git/htdocs#master
    package: https://helix-pages.anywhere.run/pages_7_3_0

  - name: gcf
    code: *defaultRepo
    content: https://github.com/adobe/helix-pages.git#master
    static: https://github.com/adobe/helix-pages.git/htdocs#master
    # universal runtime, on google cloud functions.
    package: https://helix-pages.anywhere.run/pages_7_3_0
    version-lock:
      env: google

  - name: gcf-ci
    code: *defaultRepo
    content: https://github.com/adobe/helix-pages.git#master
    static: https://github.com/adobe/helix-pages.git/htdocs#master
    # universal runtime (CI), on google cloud functions.
    package: https://helix-pages-ci.anywhere.run/pages_7_3_0
    version-lock:
      env: google

  - name: universal-ci
    code: *defaultRepo
    content: https://github.com/adobe/helix-pages.git#master
    static: https://github.com/adobe/helix-pages.git/htdocs#master
    # universal runtime, using the helix-pages-ci subdomain
    package: https://helix-pages-ci.anywhere.run/pages_7_3_0

  - name: universal-prod
    code: *defaultRepo
    content: https://github.com/adobe/helix-pages.git#master
    static: https://github.com/adobe/helix-pages.git/htdocs#master
    # universal runtime, using the helix-pages subdomain
    package: https://helix-pages.anywhere.run/pages_7_3_0
