#
# Helix Configuration
#
version: 1

definitions:
  defaults:
    # default repository. set to git remote repository before deployment
    - &defaultRepo https://github.com/adobe/helix-pages.git#master

strains:
  - name: default
    code: *defaultRepo
    content: https://github.com/adobe/helix-pages.git#master
    static: https://github.com/adobe/helix-pages.git/htdocs#master
    package: helix-pages/a3c8032dea6de1a2d00efd92eaadf695fc420322
