#
# Helix Configuration
#
version: 1

definitions:
  defaults:
    # default repository. set to git remote repository before deployment
    - &defaultRepo https://github.com/tripodsan/helix-pages.git#master

strains:
  - name: default
    code: *defaultRepo
    content: https://github.com/tripodsan/helix-pages.git#master
    static: https://github.com/tripodsan/helix-pages.git/htdocs#master
    package: tripod/github-com--tripodsan--helix-pages--master-dirty
