version: 2.1

executors:
  node8:
    docker:
      # use latest node 8 on debian 8 (jessie)
      - image: circleci/node:8-jessie
    environment:
      NPM_CONFIG_PREFIX: ~/.npm-global

commands:
  setup:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
      - run:
          name: install npm 6.11.2
          command: sudo npm -g install npm@6.11.2
      - run:
          name: Installing Dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
      - run:
          name: prepare test git user
          command: git config --global user.email "circleci@project-helix.page" && git config --global user.name "CircleCi Build"

jobs:
  build:
    executor: node8
    steps:
      - setup
      - run:
          name: Lint
          command: npm run lint

  init_hlxPagesSmokeTest:
    executor: node8
    steps:
      - setup
      - run:
          name: Installing Helix CLI
          command: npm install @adobe/helix-cli@">=5" --save=false
      - run:
          name: Build Templates
          command: npx hlx build
      - run:
          name: Deploy to Adobe I/O Runtime
          command: npx hlx deploy --add test_$CIRCLE_BUILD_NUM | cat
      - run:
          name: Compute TEST_DOMAIN and TEST_SERVICE
          command: |
              modulo=$(expr $CIRCLE_BUILD_NUM % 3 + 1)
              name="TEST_DOMAIN_$modulo"
              TEST_DOMAIN=${!name}
              name="TEST_SERVICE_$modulo"
              TEST_SERVICE=${!name}
              # "pass" the variable to the next steps...
              echo "export TEST_DOMAIN=$TEST_DOMAIN" >> $BASH_ENV
              echo "export TEST_SERVICE=$TEST_SERVICE" >> $BASH_ENV
              # debug logs
              echo "TEST_DOMAIN has been found - $TEST_DOMAIN"
              echo "TEST_SERVICE has been found - $TEST_SERVICE"
      - run:
          name: Echo
          command: echo "TEST_SERVICE - $TEST_DOMAIN"
      - run:
          name: Publish to Fastly
          command: npx hlx publish --custom-vcl='vcl/extensions.vcl' --fastly-serviceid $TEST_SERVICE | cat
      - persist_to_workspace:
          root: /home/circleci
          paths:
            # for whatever reason, working directoy is project.
            - project
            - .npm

  run_hlxPagesSmokeTest:
    executor: node8
    steps:
      - attach_workspace:
          at: /home/circleci

      - run:
          name: Echo
          command: echo "TEST_DOMAIN - $TEST_DOMAIN"

      - run:
          name: Run Helix Pages smoke tests
          command: npm run test:hlxPagesSmokeTest

  finalize_hlxPagesSmokeTest:
    executor: node8
    steps:
      - attach_workspace:
          at: /home/circleci

      - store_test_results:
          path: junit

      - store_artifacts:
          path: junit

      - save_cache:
          paths:
          - /home/circleci/.npm
          key: v5-dependencies-{{ arch }}-continuous-npm-cache

  publish:
    executor: node8
    steps:
      - setup

      - run:
          name: Installing Helix CLI
          command: npm install @adobe/helix-cli@">=5" --save=false

      - run:
          name: Build Templates
          command: npx hlx build

      - run:
          name: Reset Working Copy
          command: git status; git checkout -- . ; git pull

      - run:
          name: Deploy to Adobe I/O Runtime
          command: npx hlx deploy | cat

      - run:
          name: Publish to Fastly
          command: npx hlx publish --custom-vcl='vcl/extensions.vcl' | cat

      - add_ssh_keys
      - run:
          name: Commit helix config to master
          command: |
            git checkout master
            git pull --tags origin
            git commit -am "🚢 enshrining config post-deploy [ci skip]"

      - run:
          name: Tag known good deploy
          command: |
            git tag `date "+known-good-%Y%m%d%H%M%S"`
            git push --tags origin master

      - run:
          name: Semantic Release
          command: npm run semantic-release

workflows:
  version: 2
  build:
    jobs:
      - build
      - init_hlxPagesSmokeTest:
          requires:
            - build
      - run_hlxPagesSmokeTest:
          requires:
            - init_hlxPagesSmokeTest
      - finalize_hlxPagesSmokeTest:
          requires:
            - run_hlxPagesSmokeTest
      - publish:
          requires:
            - finalize_hlxPagesSmokeTest
          filters:
            branches:
              only: master
