on:
  push:
    branches:
      - master

jobs:
  ci_trigger:
    runs-on: ubuntu-latest
    name: Clear helix pages cache
    steps:
      - name: Trigger
        id: trigger
        uses: adobe-rnd/github-purge-cache-action@master
        with:
          helix-url: https://www.hlx.live/
          repo-token: ${{ secrets.GITHUB_TOKEN }}
